services:
  - type: web
    name: solarkits-erp-backend
    env: node
    rootDir: solar/solar-server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://frabjous-sherbet-c11932.netlify.app
