import {
  LayoutDashboard,
  Users,
  ShoppingCart,
  Truck,
  Package,
  Store,
  Building2,
  CheckCircle2,
  BriefcaseBusiness,
  Workflow,
  Settings,
  FileText,
  Home,
  MapPin,
  ClipboardList,
  Wrench,
  TrendingUp,
  Activity,
  FileBarChart,
  UserCheck,
  UserCog,
  Store as StoreIcon,
  Building,
} from 'lucide-react';

export const SIDEBAR_NAVIGATION = [
  {
    id: 'dashboard',
    name: 'Dashboard',
    icon: LayoutDashboard,
    children: [
      { name: 'User Performance', isGroup: true, children: [
        { name: 'Partner Manager Dashboard', href: '/admin/dashboard/user-performance/partner-manager' },
        { name: 'Partner Dashboard', href: '/admin/dashboard/user-performance/partner' },
        { name: 'Dealer Manager Dashboard', href: '/admin/dashboard/user-performance/dealer-manager' },
        { name: 'Dealer Dashboard', href: '/admin/dashboard/user-performance/dealer' },
      ]},
      { name: 'Orders', icon: ShoppingCart, href: '/admin/dashboard/orders' },
      { name: 'Orders by Loan', icon: FileBarChart, href: '/admin/dashboard/orders-by-loan' },
      { name: 'Installer', icon: Users, href: '/admin/dashboard/installer' },
      { name: 'Delivery', icon: Truck, href: '/admin/dashboard/delivery' },
      { name: 'Inventory', icon: Package, href: '/admin/dashboard' },
      { name: 'Vendors', icon: Store, href: '/admin/dashboard/vendors' },
    ]
  },
  {
    id: 'departments',
    name: 'Departments',
    icon: Building2,
    children: [
      { name: 'Organization chart', icon: Users, href: '/admin/departments/organization-chart' },
    ],
  },
  { id: 'approvals', name: 'Approvals', icon: CheckCircle2, href: '/admin/approvals' },
  {
    id: 'projectManagement',
    name: 'Project Management',
    icon: BriefcaseBusiness,
    children: [
      { name: 'Manage', href: '/admin/project-management', icon: Settings },
      { name: 'Track', href: '/admin/project-management/track', icon: Activity },
    ],
  },
  {
    id: 'operations',
    name: 'Operations',
    icon: Workflow,
    children: [
      { name: 'Our Warehouse', icon: Building, href: '/admin/operations/warehouse' },
      { name: 'Add Inventory Request', icon: Package, href: '/admin/operations/add-inventory' },
      { name: 'Inventory Management', icon: Store, href: '/admin/operations/inventory-management' },
      {
        id: 'settingsBrand',
        name: 'Brand Manufacturer',
        icon: StoreIcon,
        isGroup: true,
        children: [
          { name: 'Add Brand Manufacturer', href: '/admin/operations/brand/add-brand-manufacturer' },
          { name: 'Brand Supplier Overview', href: '/admin/operations/brand/supplier-overview' },
        ],
      },
    ],
  },
  {
    id: 'settings',
    name: 'Settings',
    icon: Settings,
    children: [
      {
        id: 'settingsLocation',
        name: 'Location Settings',
        icon: MapPin,
        isGroup: true,
        children: [
          { name: 'Setup Locations', href: '/admin/settings/location/setup-locations' },
        ],
      },
      {
        id: 'settingsHr',
        name: 'HR Settings',
        icon: UserCog,
        isGroup: true,
        children: [
          { name: 'Role Settings', href: '/admin/settings/hr/role-settings' },
          { name: 'Create Department', href: '/admin/settings/hr/create-department' },
          { name: 'Department-wise Modules', href: '/admin/settings/hr/department-wise-modules' },
          { name: 'Temporary Incharge Setting', href: '/admin/settings/hr/temporary-incharge-setting' },
          { name: 'Leave Approvals', href: '/admin/settings/hr/leave-approvals' },
          { name: 'Resign Approvals', href: '/admin/settings/hr/resign-approvals' },
        ],
      },
      {
        id: 'settingsVendor',
        name: 'Vendor Settings',
        icon: Store,
        isGroup: true,
        children: [
          { name: 'Installer Vendors', href: '/admin/settings/vendor/installer-vendors' },
          { name: 'Supplier Type', href: '/admin/settings/vendor/supplier-type' },
          { name: 'Supplier Vendors', href: '/admin/settings/vendor/supplier-vendors' },
        ],
      },
      {
        id: 'settingsSales',
        name: 'Sales Settings',
        icon: TrendingUp,
        isGroup: true,
        children: [
          { name: 'Set Price', href: '/admin/settings/sales/set-price' },
          { name: 'Set Price For AMC', href: '/admin/settings/sales/set-price-amc' },
          { name: 'Offers', href: '/admin/settings/sales/offers' },
          { name: 'Solar Panel Bundle Setting', href: '/admin/settings/sales/solar-panel-bundle-setting' },
        ],
      },
      {
        id: 'settingsMarketing',
        name: 'Marketing Settings',
        icon: BriefcaseBusiness,
        isGroup: true,
        children: [
          { name: 'Campaign Management', href: '/admin/settings/marketing/campaign-management' },
        ],
      },
      {
        id: 'settingsOperations',
        name: 'Settings Operations',
        icon: Workflow,
        isGroup: true,
        children: [
          {
            id: 'settingsDelivery',
            name: 'Delivery Settings',
            icon: Truck,
            isGroup: true,
            children: [
              { name: 'Delivery Type', href: '/admin/settings/delivery/delivery-type' },
              { name: 'Vehicle Selection', href: '/admin/settings/delivery/vehicle-selection' },
              { name: 'Vendor Delivery Plan', href: '/admin/settings/delivery/vendor-delivery-plan' },
            ],
          },
          {
            id: 'settingsInventory',
            name: 'Inventory Management',
            icon: Package,
            isGroup: true,
            children: [
              { name: 'Inventory Overview', href: '/admin/settings/inventory/inventory-overview' },
              { name: 'Restock Order Limit', href: '/admin/settings/inventory/restock-order-limit' },
              { name: 'Combokit Brand Overview', href: '/admin/settings/inventory/combokit-brand-overview' },
            ],
          },
          {
            id: 'settingsOrderProcurement',
            name: 'Order Procurement',
            icon: ShoppingCart,
            isGroup: true,
            children: [
              { name: 'Order Procurement', href: '/admin/settings/order-procurement' },
            ],
          },
        ],
      },
      {
        id: 'settingsInstaller',
        name: 'Installer Settings',
        icon: Users,
        isGroup: true,
        children: [
          { name: 'Solar Installer', href: '/admin/settings/installer/solar-installer' },
          { name: 'Installer Tool Requirements', href: '/admin/settings/installer/tool-requirements' },
          { name: 'Rating Setting', href: '/admin/settings/installer/rating-setting' },
          { name: 'Installer Agency Plans', href: '/admin/settings/installer/agency-plans' },
        ],
      },
      {
        id: 'settingsProduct',
        name: 'Product Configuration',
        icon: LayoutDashboard,
        isGroup: true,
        children: [
          { name: 'Add Project Type', href: '/admin/settings/product/add-project-type' },
          { name: 'Add Project Category', href: '/admin/settings/product/add-project-category' },
          { name: 'Add Product', href: '/admin/settings/product/add-product' },
          { name: 'SKU', href: '/admin/settings/product/sku' },
          { name: 'Price Master', href: '/admin/settings/product/price-master' },
          { name: 'Add Unit Management', href: '/admin/settings/product/add-unit-management' },
        ],
      },
      {
        id: 'settingsCombokit',
        name: 'ComboKit',
        icon: Package,
        isGroup: true,
        children: [
          { name: 'Create Solarkit', href: '/admin/settings/combokit/create-solarkit' },
          { name: 'Create AMC Plans', href: '/admin/settings/combokit/create-amc' },
          { name: 'AMC Services', href: '/admin/settings/combokit/amc-services' },
          { name: 'Solarkit Bundle Plans', href: '/admin/settings/combokit/bundle-plans' },
          { name: 'Add ComboKit', href: '/admin/settings/combokit/add-combokit' },
          { name: 'Customize Combokit', href: '/admin/settings/combokit/customize' },
          { name: 'Combokit Overview', href: '/admin/settings/combokit-overview' },
        ],
      },
      {
        id: 'settingsPartner',
        name: 'Partner Settings',
        icon: Users,
        isGroup: true,
        children: [
          { name: 'Partner Plans', href: '/admin/settings/partner/plans' },
          { name: 'Partner Points & Reward Setting', href: '/admin/settings/partner/points-rewards' },
          { name: 'Partner Onboarding Goals', href: '/admin/settings/partner/onboarding-goals' },
          { name: 'Partner Profession Type', href: '/admin/settings/partner/profession-type' },
          { name: 'Add Partner', href: '/admin/settings/partner/add-partner' },
          { name: 'Partner Manager Setting', href: '/admin/settings/partner-manager' },
          { name: 'Partner Buy Lead Setting', href: '/admin/settings/partner-buy-lead' },
        ],
      },
      {
        id: 'settingsHrms',
        name: 'HRMS Settings',
        icon: UserCog,
        isGroup: true,
        children: [
          { name: 'HRMS Settings', href: '/admin/settings/hrms/settings' },
          { name: 'Vacancy Module', href: '/admin/settings/hrms/vacancy-module' },
          { name: 'Candidates List', href: '/admin/settings/hrms/candidates' },
          { name: 'Candidate Test Setting', href: '/admin/settings/hrms/candidate-test-setting' },
          { name: 'Candidate Training Setting', href: '/admin/settings/hrms/candidate-training-setting' },
        ],
      },
      {
        id: 'settingsProject',
        name: 'Project Management Settings',
        icon: BriefcaseBusiness,
        isGroup: true,
        children: [
          { name: 'Project Journey Stage Setting', href: '/admin/settings/project/journey-stage-setting' },
          { name: 'Project Management Overdue Setting', href: '/admin/settings/project/overdue-setting' },
          { name: 'Project Management Configuration', href: '/admin/settings/project/configuration-setting' },
          { name: 'Project Documentation Setting', href: '/admin/settings/project/documentation-setting' },
          { name: 'Placeholder Name Setting', href: '/admin/settings/project/placeholder-name-setting' },
        ],
      },
      {
        id: 'settingsQuote',
        name: 'Quote',
        icon: FileText,
        isGroup: true,
        children: [
          { name: 'Quote Setting', href: '/admin/settings/quote/quote-setting' },
          { name: 'Survey BOM Setting', href: '/admin/settings/quote/survey-bom-setting' },
          { name: 'Terrace Setting', href: '/admin/settings/quote/terrace-setting' },
          { name: 'Structure Setting', href: '/admin/settings/quote/structure-setting' },
          { name: 'Building Setting', href: '/admin/settings/quote/building-setting' },
          { name: 'Discom Master', href: '/admin/settings/quote/discom-master' },
        ],
      },
      {
        id: 'settingsOverdue',
        name: 'Overdue Setting',
        icon: CheckCircle2,
        isGroup: true,
        children: [
          { name: 'Approval Overdue Setting', href: '/admin/settings/approval-overdue' },
          { name: 'Overdue Task Setting', href: '/admin/settings/overdue-task' },
          { name: 'Overdue Status Setting', href: '/admin/settings/overdue-status' },
        ],
      },
      { id: 'settingsLoan', name: 'Loan Setting', icon: FileBarChart, href: '/admin/settings/loan' },
      { id: 'settingsChecklist', name: 'Checklist Setting', icon: ClipboardList, href: '/admin/settings/checklist' },
    ],
  },
  {
    id: 'reports',
    name: 'Report',
    icon: FileText,
    children: [
      { name: 'Financial & P&L', icon: FileBarChart, href: '/admin/reports/financial-pl' },
      { name: 'Cashflow', icon: FileBarChart, href: '/admin/reports/cashflow' },
      { name: 'Inventory', icon: Package, href: '/admin/reports/inventory' },
      { name: 'Loans', icon: FileBarChart, href: '/admin/reports/loans-summary' },
      { name: 'Captable', icon: FileBarChart, href: '/admin/reports/captable' },
      { name: 'Revenue By CP Types', icon: FileBarChart, href: '/admin/reports/revenue-by-cp-types' },
      { name: 'Cluster', icon: FileBarChart, href: '/admin/reports/cluster' },
      { name: 'District', icon: FileBarChart, href: '/admin/reports/district' },
      { name: 'City', icon: FileBarChart, href: '/admin/reports/city' },
    ],
  },
];
